name: atomai
description: A new Flutter project.

version: 4.378.1+378
publish_to: none

environment: 
  sdk: '>=3.0.0 <4.0.0'


dependencies: 
  flutter: 
    sdk: flutter
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  firebase_storage: ^11.5.2
  cloud_firestore: ^4.13.2
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  firebase_messaging: ^14.7.5
  get: ^4.6.6
  connectivity_plus: ^5.0.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^8.0.1
  intl: ^0.18.1
  permission_handler: ^11.1.0
  dio: ^5.3.3
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  animated_text_kit: ^4.2.2
  flutter_tts: ^3.8.3
  jiffy: ^6.2.1
  flutter_quill: ^8.6.1
  flutter_quill_extensions: ^0.7.0
  vsc_quill_delta_to_html: ^1.0.3
  flutter_html_to_pdf: ^0.7.0
  fluttertoast: ^8.2.4
  purchases_flutter: ^6.3.0
  get_storage: ^2.1.1
  form_validator: ^2.1.1
  carousel_slider: ^4.2.1
  toggle_switch: ^2.1.0
  webview_flutter: ^4.4.2
  webview_flutter_wkwebview: ^3.9.4
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  open_filex: ^4.3.4
  share_plus: ^7.2.1
  flutter_local_notifications: ^16.1.0
  local_auth: ^2.1.7
  file_picker: ^6.1.1
  crypto: ^3.0.3
  vibration: ^1.8.3
  flutter_vibrate: ^1.3.0
  image_gallery_saver: ^2.0.3
  
dev_dependencies: 
  rename: ^2.0.1
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.16
  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon1024.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/icons/icon1024.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"


flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons_png/
    - assets/icons_png/WHITE/
    - assets/icons_png/BLACK/
    - assets/image_genarator/


  fonts: 
    - family: Mulish
      fonts: 
        - asset: assets/fonts/MulishRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/MulishRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/MulishRomanBold.ttf
          weight: 700
        - asset: assets/fonts/MulishRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MulishRegular.ttf
          weight: 400
        - asset: assets/fonts/MulishSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MulishBold.ttf
          weight: 700
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
    - family: Montserrat Alternates
      fonts: 
        - asset: assets/fonts/MontserratAlternatesMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratAlternatesSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratAlternatesBold.ttf
          weight: 700
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
